# Generated by Django 3.2.16 on 2022-10-30 07:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221030_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent_department',
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainapp.department'),
        ),
    ]
